### ISSUE TITLE
Error when running `loki init` with storybook declarative config

### ISSUE THREAD

**Issue by tr00st** [oblador/loki#217]
**Steps to reproduce:**

1. Produce a Storybook project using the new declarative config style (ie: using `.storybook/main.js`)
2. Run the `loki init` command.

**Expected result:**

`loki init` executes normally

**Actual result:**

`no such file or directory` error is raised looking for the config files.

**Details:**

Appears that the `loki init` command is hard-coded to reference config.js

https://github.com/oblador/loki/blob/d801084d954cb19ca831cc1967d9d47068e57f75/packages/runner/src/commands/init/index.js#L91

Notes on the differences are in the Storybook 5.3 release notes:

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#to-mainjs-configuration

Should be possible to work around for now by porting to the old config style for this operation. The new config format isn't mandatory, but config.js formatting is apparently now deprecated.

Command output included below for reference.

```
PS C:\Projects\user-system-test-standalone> npx loki init
loki init v0.20.1
Adding loki defaults to package.json
ENOENT: no such file or directory, open 'C:\Projects\user-system-test-standalone\.storybook/config.js'
Error: ENOENT: no such file or directory, open 'C:\Projects\user-system-test-standalone\.storybook/config.js'
    at Object.openSync (fs.js:451:3)
    at Object.readFileSync (fs.js:353:35)
    at init (C:\Projects\user-system-test-standalone\node_modules\@loki\runner\src\commands\init\index.js:92:25)
    at run (C:\Projects\user-system-test-standalone\node_modules\@loki\runner\src\cli.js:41:11)
    at Object.<anonymous> (C:\Projects\user-system-test-standalone\node_modules\@loki\runner\bin\loki:3:22)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
```

**Comment by tr00st** [comment]
Looks like there might be some more severe issues. The parser used by Storybook for loading `main.js` doesn't appear to allow ES `import`s, and `require('loki/configure-react');` doesn't seem sufficient to load the Loki addon. I'll try and look further into config on my end in case there are some other issues, but it looks like a bug at first glance.

Config:
```
require('loki/configure-react');

module.exports = {
  stories: ['../src/**/*.stories.js'],
  addons: [
    '@storybook/preset-create-react-app',
    '@storybook/addon-actions',
    '@storybook/addon-links',
    'loki/configure-react',
  ],
};
```

Command output:
```
PS C:\Projects\user-system-test-standalone> npx loki
loki test v0.20.1
 FAIL  chrome.app
       Fetching stories
       Loki addon not registered. Add `import 'loki/configure-react'` to your config.js file.
Some visual tests failed to run
```

**Comment by oblador** [comment]
This should have been fixed in [0.20.2](https://github.com/oblador/loki/releases/tag/v0.20.2], would you mind verifying that for me?

**Comment by tr00st** [comment]
Thanks! I'll try and take a look over the next couple of days.

**Comment by oblador** [comment]
Closing due to inactivity

**Comment by tr00st** [comment]
Yep, all looks good (issues were related to having multiple storybook-capable projects hanging about).

Thanks for the solution - and apologies again for taking so long to respond!
