### ISSUE TITLE
chrome.docker with Error: Timeout

### ISSUE THREAD

**Issue by rwieruch** [oblador/loki#222]
Using https://github.com/AvnerCohen/lok-dnd-repro on my MacOS with this [Docker Setup](https://www.robinwieruch.de/docker-macos). This seems to work for others: https://github.com/oblador/loki/issues/183#issuecomment-600013794 However, when I try to run the Loki tests in Docker, I get:

```
> loki test

loki test v0.20.1
 FAIL  chrome.docker
       Starting
       Chrome failed to start with errors "", "DevTools listening on ws://0.0.0.0:53273/de
vtools/browser/e8bfbe46-db1c-4e8d-b209-6b5cc90e077d"
Some visual tests failed to run
```

If I `console.log` the error at https://github.com/oblador/loki/blob/d801084d954cb19ca831cc1967d9d47068e57f75/packages/target-chrome-docker/src/create-chrome-docker-target.js#L138 I get:

```
loki test v0.20.1
 RUNS  chrome.docker: Starting
Error: Timeout
    at Timeout._onTimeout (/Users/mydspr/Developer/Repos/lok-dnd-repro/node_modules/wait-on/lib/wait-on.js:113:10)
    at listOnTimeout (internal/timers.js:549:17)
 FAIL  chrome.docker
       Starting
       Chrome failed to start with error "DevTools listening on ws://0.0.0.0:57617/devtool
s/browser/52ca57e9-6fab-4553-b46c-162e8b1a0657"
Some visual tests failed to run
```

**What I tried:**

* If I use `chrome.app`, everything works fine.
* I reproduced this issue on another MacOS system with the same Docker setup from above.
* Tried to increase the timeout integer https://github.com/oblador/loki/issues/38, didn't help though.
* Tried Chrome flags https://github.com/oblador/loki/issues/143 didn't work.

**Comment by AvnerCohen** [comment]
What do you see on `docker ps` on your local machine ?

**Comment by rwieruch** [comment]
```
 [52] → docker ps
CONTAINER ID        IMAGE                                           COMMAND                  CREATED             STATUS              PORTS                                               NAMES
e466e6a9dd9c        yukinying/chrome-headless-browser:82.0.4083.0   "/usr/bin/dumb-init …"   2 hours ago         Up 2 hours          0.0.0.0:57617->57617/tcp                            epic_khorana
b04f9edca8fd        yukinying/chrome-headless-browser:82.0.4083.0   "/usr/bin/dumb-init …"   2 hours ago         Up 2 hours          0.0.0.0:56287->56287/tcp                            strange_chandrasekhar
602e269bc783        yukinying/chrome-headless-browser:82.0.4083.0   "/usr/bin/dumb-init …"   2 hours ago         Up 2 hours          0.0.0.0:55042->55042/tcp                            goofy_colden
37ca7070d852        yukinying/chrome-headless-browser:82.0.4083.0   "/usr/bin/dumb-init …"   3 hours ago         Up 3 hours          0.0.0.0:53671->53671/tcp                            frosty_hermann
ea168122b85a        yukinying/chrome-headless-browser:82.0.4083.0   "/usr/bin/dumb-init …"   3 hours ago         Up 3 hours          0.0.0.0:53357->53357/tcp                            stupefied_saha
4c71e3a01e0d        yukinying/chrome-headless-browser:82.0.4083.0   "/usr/bin/dumb-init …"   3 hours ago         Up 3 hours          0.0.0.0:53273->53273/tcp                            keen_turing
238c7124e87d        yukinying/chrome-headless-browser:82.0.4083.0   "/usr/bin/dumb-init …"   3 hours ago         Up 3 hours          0.0.0.0:53149->53149/tcp                            stupefied_wilbur
3c38c007f0a8        yukinying/chrome-headless-browser:82.0.4083.0   "/usr/bin/dumb-init …"   3 hours ago         Up 3 hours          0.0.0.0:53072->53072/tcp                            recursing_herschel
4d7ae63aa47e        yukinying/chrome-headless-browser:82.0.4083.0   "/usr/bin/dumb-init …"   3 hours ago         Up 3 hours          0.0.0.0:53005->53005/tcp                            wizardly_black
6b3b6c256ac6        yukinying/chrome-headless-browser:82.0.4083.0   "/usr/bin/dumb-init …"   3 hours ago         Up 3 hours          0.0.0.0:52430->52430/tcp                            wizardly_shaw
1eb8fea27089        yukinying/chrome-headless-browser:82.0.4083.0   "/usr/bin/dumb-init …"   4 hours ago         Up 4 hours          0.0.0.0:52356->52356/tcp                            boring_joliot
e58d35959178        yukinying/chrome-headless:63.0.3230.2           "/chrome/headless_sh…"   4 hours ago         Up 4 hours          0.0.0.0:52291->52291/tcp, 0.0.0.0:32779->9222/tcp   gracious_turing
7631e6a781eb        yukinying/chrome-headless-browser:82.0.4083.0   "/usr/bin/dumb-init …"   4 hours ago         Up 4 hours          0.0.0.0:52230->52230/tcp                            beautiful_banach
7b0e34d91a5a        yukinying/chrome-headless-browser:82.0.4083.0   "/usr/bin/dumb-init …"   4 hours ago         Up 4 hours          0.0.0.0:51997->51997/tcp                            priceless_hoover
ecf8e877dce5        yukinying/chrome-headless-browser:82.0.4083.0   "/usr/bin/dumb-init …"   4 hours ago         Up 4 hours          0.0.0.0:51935->51935/tcp                            crazy_carson
8e3be4def281        yukinying/chrome-headless-browser:82.0.4083.0   "/usr/bin/dumb-init …"   4 hours ago         Up 4 hours          0.0.0.0:51867->51867/tcp                            jovial_wozniak
c73bd00db074        yukinying/chrome-headless:63.0.3230.2           "/chrome/headless_sh…"   4 hours ago         Up 4 hours          0.0.0.0:51785->51785/tcp, 0.0.0.0:32778->9222/tcp   xenodochial_elion
51fed5d99636        yukinying/chrome-headless-browser:82.0.4083.0   "/usr/bin/dumb-init …"   4 hours ago         Up 4 hours          0.0.0.0:51648->51648/tcp                            cranky_feynman
1ad5d6829a81        yukinying/chrome-headless-browser:82.0.4083.0   "/usr/bin/dumb-init …"   4 hours ago         Up 4 hours          0.0.0.0:51587->51587/tcp                            sharp_hoover
4126d0d204a4        yukinying/chrome-headless-browser:82.0.4083.0   "/usr/bin/dumb-init …"   4 hours ago         Up 4 hours          0.0.0.0:51438->51438/tcp                            mystifying_shirley
c9ec4a8e76c7        yukinying/chrome-headless:63.0.3230.2           "/chrome/headless_sh…"   5 hours ago         Up 5 hours          0.0.0.0:50942->50942/tcp, 0.0.0.0:32777->9222/tcp   brave_stonebraker
a7f3fa269089        yukinying/chrome-headless:63.0.3230.2           "/chrome/headless_sh…"   5 hours ago         Up 5 hours          0.0.0.0:50862->50862/tcp, 0.0.0.0:32776->9222/tcp   romantic_feynman
ae03d0a3f0ff        yukinying/chrome-headless:63.0.3230.2           "/chrome/headless_sh…"   5 hours ago         Up 5 hours          0.0.0.0:50750->50750/tcp, 0.0.0.0:32775->9222/tcp   pensive_mclean
9440988b3bdb        yukinying/chrome-headless:63.0.3230.2           "/chrome/headless_sh…"   5 hours ago         Up 5 hours          0.0.0.0:50106->50106/tcp, 0.0.0.0:32772->9222/tcp   reverent_wiles
2afc5ca528d7        yukinying/chrome-headless:63.0.3230.2           "/chrome/headless_sh…"   5 hours ago         Up 5 hours          0.0.0.0:49921->49921/tcp, 0.0.0.0:32771->9222/tcp   magical_shamir
8b97c5b4b2f9        yukinying/chrome-headless:63.0.3230.2           "/chrome/headless_sh…"   5 hours ago         Up 5 hours          0.0.0.0:49698->49698/tcp, 0.0.0.0:32770->9222/tcp   distracted_chaplygin
13b8b38ab72d        yukinying/chrome-headless:63.0.3230.2           "/chrome/headless_sh…"   5 hours ago         Up 5 hours          0.0.0.0:49529->49529/tcp, 0.0.0.0:32769->9222/tcp   modest_babbage
0c6231e86d27        yukinying/chrome-headless:63.0.3230.2           "/chrome/headless_sh…"   5 hours ago         Up 5 hours          0.0.0.0:49439->49439/tcp, 0.0.0.0:32768->9222/tcp   determined_greider
```

**Comment by AvnerCohen** [comment]
ok.. so I would suggest to try and clean this up as a first step.

**Comment by rwieruch** [comment]
Cleaned up everything now:

```
 [62] → docker images
REPOSITORY                            TAG                 IMAGE ID            CREATED             SIZE

 [63] → docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

Then I do loki test:

```
> loki test

loki test v0.20.1
 RUNS  chrome.docker: Starting
Host: 127.0.0.1, Port: 61673
Error: Timeout
    at Timeout._onTimeout (/Users/mydspr/Developer/Repos/lok-dnd-repro/node_modules/wait-on/lib/wait-on.js:113:10)
    at listOnTimeout (internal/timers.js:549:17)
 FAIL  chrome.docker
       Starting
       Chrome failed to start with errors "", "DevTools listening on ws://0.0.0.0:61673/devtools/browser/548287aa-47b1-4994-ae30-7c88e170cfc5"
Some visual tests failed to run
```

The with `docker ps` I get:

```
 [71] → docker ps
CONTAINER ID        IMAGE                                           COMMAND                  CREATED             STATUS              PORTS                      NAMES
33cd8fb7d3a4        yukinying/chrome-headless-browser:82.0.4083.0   "/usr/bin/dumb-init …"   50 seconds ago      Up 48 seconds       0.0.0.0:61673->61673/tcp   dazzling_dewdney
```

With `docker images` I get:

```
 [72] → docker images
REPOSITORY                            TAG                 IMAGE ID            CREATED             SIZE
yukinying/chrome-headless-browser     82.0.4083.0         772fde969100        4 days ago          663MB
```

With `docker-machine ip default` I get

```
 [73] → docker-machine ip default
192.168.99.100
```

**Comment by AvnerCohen** [comment]
What do you get with:
```sh
$> wait-on tcp: 61673
```

**Comment by rwieruch** [comment]
I have used this [wait-on](https://github.com/jeffbski/wait-on):

```
 [79] → wait-on tcp:61673

```

It's just stuck there. Should I run this in a separate command line window while I try the loki test again?

**Comment by AvnerCohen** [comment]
Cool, so yeah, this is very similar to what I see in circleci.
No idea what could be the root cause on that I afraid.

**Comment by rwieruch** [comment]
> Cool, so yeah, this is very similar to what I see in circleci.
> No idea what could be the root cause on that I afraid.

If you have any ideas to track the issue down, let me know and I will try it locally. Debugging this on CI must be a pain ...

**Comment by codrin-iftimie** [comment]
I've did some research myself regarding docker-in-docker, and I ended up throwing that entire idea to the trash. In CI that this in a docker container it think it's easier to use chrome.app. More details here -> https://github.com/oblador/loki/pull/129#issuecomment-740722629
