### ISSUE TITLE
Uncaught TypeError on yarn loki update

### ISSUE THREAD

**Issue by ebmocces** [oblador/loki#30]
Hi, we're trying to get the latest version of Loki working with React & Lerna, but when running `yarn loki update -- --port 8080` I get:

```
somewhere:react-project ebmocces$ yarn loki update -- --port 8080
yarn loki v0.27.5
$ "/src/react-project/node_modules/.bin/loki" "update" "--port" "8080"
loki update v0.7.0
 ✔ Chrome (app)
Error: Uncaught [TypeError: source.close is not a function]
    at reportException (/src/uitk-react/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
    at Timeout.callback (/src/uitk-react/node_modules/jsdom/lib/jsdom/browser/Window.js:544:7)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5) TypeError: source.close is not a function
    at handleDisconnect (evalmachine.<anonymous>:42296:12)
    at Window.<anonymous> (evalmachine.<anonymous>:42271:7)
    at Timeout.callback (/src/uitk-react/node_modules/jsdom/lib/jsdom/browser/Window.js:542:19)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
Done in 22.00s.
```

Any ideas? I've tried looking into jsdom to see what's causing it to fall over, but can't seem to see anything.

Node v8.1.2
React v16.0.0
Lerna v2.4.0

**Comment by oblador** [comment]
This should be fixed by https://github.com/oblador/loki/pull/35
