### ISSUE TITLE
createAsyncCallback doesn't work with Args API

### ISSUE THREAD

**Issue by donaldpipowitch** [oblador/loki#358]
[Test Case](https://github.com/donaldpipowitch/loki-create-async-callback-args)

When `createAsyncCallback()` is used as part of the [Args API](https://storybook.js.org/docs/react/writing-stories/args) Loki has troubles fetching the stories.

```
const Template = (args) => <DelayedComponent {...args} />;

export const Hello = Template.bind({});
Hello.args = {
  text: 'Hello',
  onDone: createAsyncCallback(),
};

export const World = Template.bind({});
World.args = {
  text: 'World',
  onDone: createAsyncCallback(),
};
```

```
Failed fetching stories because the server is down
```

**Comment by emlai** [comment]
I also get:

```
/Users/emlai/src/epic-ui/node_modules/.pnpm/yoga-layout-prebuilt@1.10.0/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at writeFile (node:fs:2168:5)
    at go$writeFile (/Users/emlai/src/epic-ui/node_modules/.pnpm/graceful-fs@4.2.10/node_modules/graceful-fs/graceful-fs.js:138:14)
    at Object.writeFile (/Users/emlai/src/epic-ui/node_modules/.pnpm/graceful-fs@4.2.10/node_modules/graceful-fs/graceful-fs.js:135:12)
    at /Users/emlai/src/epic-ui/node_modules/.pnpm/fs-extra@9.1.0/node_modules/fs-extra/lib/output/index.js:18:27
    at /Users/emlai/src/epic-ui/node_modules/.pnpm/universalify@2.0.0/node_modules/universalify/index.js:22:54 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

when running the whole visual test suite. Using `--storiesFilter` to run only some tests seems to not give that error enough time to pop up.

**Comment by Ajdija** [comment]
This was a showstopper for us for a long time
