### ISSUE TITLE
Chromium failures with bigger stories

### ISSUE THREAD

**Issue by chriskalmar** [oblador/loki#363]
This is a great project and we are trying to make it work with our current Storybook.
At the moment we are faced with 2 errors whenever we hit a bigger story. 
The hope was that by reducing the concurrency to 1 by using `--chromeConcurrency` the errors would go away.
Unfortunately, they still occur.

For reference what we mean by "bigger" stories:
Resolutions of e.g. 800 × 7180

Error type 1:
```
RUNS chrome.app/chrome.laptop/pages/Upsell Pages/Variants
/app/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at writeFile (node:fs:2106:5)
    at go$writeFile (/app/node_modules/graceful-fs/graceful-fs.js:138:14)
    at Object.writeFile (/app/node_modules/graceful-fs/graceful-fs.js:135:12)
    at /app/node_modules/fs-extra/lib/output/index.js:18:27
    at /app/node_modules/universalify/index.js:22:54 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

Error type 2:
```
FAIL chrome.app/TESTS: Some tasks failed to run
FAIL chrome.app: Some tasks failed to run
Chrome could not be killed kill ESRCH
Error: Chrome could not be killed kill ESRCH
    at /app/node_modules/chrome-launcher/dist/chrome-launcher.js:282:28
    at new Promise (<anonymous>)
    at Launcher.kill (/app/node_modules/chrome-launcher/dist/chrome-launcher.js:262:16)
    at Object.<anonymous> (/app/node_modules/chrome-launcher/dist/chrome-launcher.js:54:29)
    at Generator.next (<anonymous>)
    at /app/node_modules/chrome-launcher/dist/chrome-launcher.js:13:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/chrome-launcher/dist/chrome-launcher.js:9:12)
    at Object.kill (/app/node_modules/chrome-launcher/dist/chrome-launcher.js:49:28)
    at Object.stop (/app/node_modules/@loki/target-chrome-app/src/create-chrome-app-target.js:29:22)
```

The setup that we have at the moment is a Docker container with Chromium installed and running Loki inside it by mounting in the static storybook build.

Config-wise we use these flags:
`--chromeFlags="--headless --disable-gpu --hide-scrollbars --no-sandbox" `

And the `loki.config.js` looks like this:
```
module.exports = {
  fetchFailIgnore: false,
  configurations: {
    'chrome.laptop': {
      target: 'chrome.app',
      width: 1366,
      height: 768,
    },
  },
};
```

Our Dockerfile is having this:
```
FROM node:16-alpine

RUN apk add chromium

WORKDIR /app

COPY package.json .
COPY package-lock.json .
COPY src src/
COPY loki.config.js .
COPY tsconfig.json .
COPY loadEnv.js .
COPY entrypoint.sh /entrypoint.sh

RUN npm install
RUN npm run build

ENV NODE_ENV production

ENTRYPOINT ["/entrypoint.sh"]
```

And the entrypoint looks like this:
```
./node_modules/.bin/loki \
--verboseRenderer \
--requireReference \
--reactUri file:$STORYBOOK_PATH \
--chromeFlags="--headless --disable-gpu --hide-scrollbars --no-sandbox" \
--chromeConcurrency=$CONCURRENCY \
test
```

Do you have any ideas what the cause for such errors could be?

**Comment by levito** [comment]
I had the same issue, also some team mates experienced this. It was happening on our Macs only and could be solved by a simple Docker update.
