### ISSUE TITLE
'Error: Unexpected token <' when making 'yarn loki update'

### ISSUE THREAD

**Issue by varya** [oblador/loki#39]
I'm trying to start using loki, but get error making reference images:

```
Unexpected token <
Error: Unexpected token <
    at createError (/Users/varyastepanova/WebDev/SC5/design-systems/ds-workshop/ds-workshop-storybook-boilerplate/node_modules/loki/src/targets/chrome/fetch-storybook.js:10:14)
    at Worker.worker.on.message (/Users/varyastepanova/WebDev/SC5/design-systems/ds-workshop/ds-workshop-storybook-boilerplate/node_modules/loki/src/targets/chrome/fetch-storybook.js:33:16)
```

node@7.10.1 (also reproduced this at node@8.9.2)

**Comment by oblador** [comment]
Hi Varya, happy to hear you're trying out loki! Do you have this project somewhere where I can try to reproduce the problem?

**Comment by varya** [comment]
@oblador Hi. This branch https://github.com/SC5/ds-workshop-storybook-boilerplate/tree/visual-regression-tests-loki
Storybook to be run with `yarn start`.

**Comment by oblador** [comment]
@varya Thanks, that's just what I needed. Can you confirm this PR fixes your problem? https://github.com/oblador/loki/pull/43

**Comment by varya** [comment]
@oblador With that branch, I have a different error:

```
Varyas-MBP: ~/WebDev/SC5/design-systems/ds-workshop/ds-workshop-storybook-boilerplate 𝒪𝓃 visual-regression-tests-loki ±
  𝒟ℴ yarn loki update
yarn run v1.3.2
$ /Users/varya/WebDev/SC5/design-systems/ds-workshop/ds-workshop-storybook-boilerplate/node_modules/.bin/loki update
loki update v0.8.0
 ❯ Chrome (docker)
   ✔ Start
   ✖ Fetch list of stories
     → Module build failed: Error: ENOENT: no such file or directory, open '/Users/varya/WebDev/SC5/design-systems/ds-workshop/ds-workshop-storybook-boilerplate/node_modules/loki/configure-react.js'
     Test chrome.laptop
     Stop
Module build failed: Error: ENOENT: no such file or directory, open '/Users/varya/WebDev/SC5/design-systems/ds-workshop/ds-workshop-storybook-boilerplate/node_modules/loki/configure-react.js'
Error: Module build failed: Error: ENOENT: no such file or directory, open '/Users/varya/WebDev/SC5/design-systems/ds-workshop/ds-workshop-storybook-boilerplate/node_modules/loki/configure-react.js'
    at createError (/Users/varya/WebDev/SC5/OpenSource/loki/src/targets/chrome/fetch-storybook.js:10:14)
    at Worker.worker.on.message (/Users/varya/WebDev/SC5/OpenSource/loki/src/targets/chrome/fetch-storybook.js:33:16)
    at emitTwo (events.js:131:20)
    at Worker.emit (events.js:214:7)
    at ChildProcess.Worker.process.on (internal/cluster/worker.js:42:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by MACSkeptic** [comment]
had the same problem, #43 fixed it for me
