### ISSUE TITLE
Upgrade to react-18 issue on CI

### ISSUE THREAD

**Issue by vbonnefond** [oblador/loki#401]
Following react-18 upgrade, I got this error on CI :
`/builds/nmKybPR1/2/navops/unification/navops/ui/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at writeFile (node:fs:2106:5)
    at go$writeFile (/builds/nmKybPR1/2/navops/unification/navops/ui/node_modules/graceful-fs/graceful-fs.js:138:14)
    at Object.writeFile (/builds/nmKybPR1/2/navops/unification/navops/ui/node_modules/graceful-fs/graceful-fs.js:135:12)
    at /builds/nmKybPR1/2/navops/unification/navops/ui/node_modules/fs-extra/lib/output/index.js:18:27
    at /builds/nmKybPR1/2/navops/unification/navops/ui/node_modules/universalify/index.js:22:54 {
  code: 'ERR_INVALID_ARG_TYPE'
}`

**Comment by techeverri** [comment]
Hey @vbonnefond 👋 

The error you got there seems to come from a package called `yoga-layout-prebuilt`.
Do you think this is somehow related to `loki`? 🤔

**Comment by vbonnefond** [comment]
Hello, 
I have the error during `yarn loki --requireReference --reactUri file:./storybook --chromeFlags='--headless --disable-gpu --hide-scrollbars --no-sandbox' --verboseRenderer` when tests are running. If I remove it, it works fine. If I remove react upgrade, it works fine. Here is more context :
```
loki test v0.28.1
RUNS chrome.app
RUNS chrome.app/START
PASS chrome.app/START
RUNS chrome.app/FETCH_STORIES
PASS chrome.app/FETCH_STORIES
RUNS chrome.app/TESTS
RUNS chrome.app/chrome.laptop.ci/Icons/Cloud Icons 24
RUNS chrome.app/chrome.laptop.ci/Icons/Cloud Icons 48
RUNS chrome.app/chrome.laptop.ci/Icons/Cloud Icons 96
RUNS chrome.app/chrome.laptop.ci/Components/SearchBox/Default
PASS chrome.app/chrome.laptop.ci/Icons/Cloud Icons 24
PASS chrome.app/chrome.laptop.ci/Components/SearchBox/Default
PASS chrome.app/chrome.laptop.ci/Icons/Cloud Icons 48
/builds/nmKybPR1/0/navops/unification/navops/ui/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at writeFile (node:fs:2106:5)
    at go$writeFile (/builds/nmKybPR1/0/navops/unification/navops/ui/node_modules/graceful-fs/graceful-fs.js:138:14)
    at Object.writeFile (/builds/nmKybPR1/0/navops/unification/navops/ui/node_modules/graceful-fs/graceful-fs.js:135:12)
    at /builds/nmKybPR1/0/navops/unification/navops/ui/node_modules/fs-extra/lib/output/index.js:18:27
    at /builds/nmKybPR1/0/navops/unification/navops/ui/node_modules/universalify/index.js:22:54 {
  code: 'ERR_INVALID_ARG_TYPE'
}
error Command failed with exit code 7.
```
`yoga-layout-prebuilt` is used by `ink` that is used by `"@loki/runner@^0.30.3"`

**Comment by oblador** [comment]
@vbonnefond Do you force react to be version 18? Npm supports multiple versions so it _shouldn't_ be an issue unless you meddle with the version resolution.

**Comment by vbonnefond** [comment]
You are right, I'm having 2 react versions in my yarn.lock: React 17.0.2 for loki and React 18.2.0 for the rest. I deactivated loki for now, I will wait for loki to to React 18.2.0

**Comment by kirilldronkin** [comment]
I recently had a chance to dig into the problem, and I have to say that `yoga-layout-prebuilt` is not the culprit - it just listens for uncaught exceptions and exits the process when some occur. I confirmed this by stripping the interactive renderer import (it uses `ink` under the hood) and the error was still there, but at that time it just didn't go through `yoga-layout-prebuilt`.

The root cause of the problem is a flaw in the handling of load timeout by `captureScreenshotForStory` from `@loki/target-chrome-core`. When a timeout exception is thrown it bypasses re-throwing and just prints a debug message, letting `undefined` to be returned. And then this `undefined` tries to be written to the file system instead of screenshot buffer by `outputFile` from `fs-extra`, which we can see in stack traces.

I don't why exactly this timeout errors started to occur, they didn't until recently, but fixing the handling of load timeouts along with setting `chromeRetries` to `1` worked for me.

**Comment by donaldpipowitch** [comment]
We see this error with Node 18 and React 17. It doesn't look like it is fixable by `chromeRetries` and I couldn't figure out so far what the problem is, sadly.

**Comment by florian-milky** [comment]
> fixing the handling of load timeouts along with setting chromeRetries worked for me

@kirilldronkin how did you do that?
Loki suddenly started to be very slow for me and I get the same issue.

**Comment by kirilldronkin** [comment]
@florian-milky here's the patch, hope it can help you.

```diff
diff --git a/node_modules/@loki/target-chrome-core/src/create-chrome-target.js b/node_modules/@loki/target-chrome-core/src/create-chrome-target.js
index 69878ef..de095d9 100644
--- a/node_modules/@loki/target-chrome-core/src/create-chrome-target.js
+++ b/node_modules/@loki/target-chrome-core/src/create-chrome-target.js
@@ -250,11 +250,7 @@ function createChromeTarget(
       }
     };
 
-    client.captureScreenshot = withRetries(
-      options.chromeRetries,
-      CAPTURING_SCREENSHOT_RETRY_BACKOFF
-    )(
-      withTimeout(
+    client.captureScreenshot = withTimeout(
         CAPTURING_SCREENSHOT_TIMEOUT,
         'captureScreenshot'
       )(async (selector = 'body') => {
@@ -328,8 +324,7 @@ function createChromeTarget(
         }
 
         return buffer;
-      })
-    );
+      });
 
     return client;
   }
@@ -402,22 +397,24 @@ function createChromeTarget(
       options.chromeSelector;
     const url = getStoryUrl(storyId);
 
-    const tab = await launchNewTab(tabOptions);
-    let screenshot;
-    try {
-      await withTimeout(options.chromeLoadTimeout)(tab.loadUrl(url, selector));
-      screenshot = await tab.captureScreenshot(selector);
-    } catch (err) {
-      if (err instanceof TimeoutError) {
-        debug(`Timed out waiting for "${url}" to load`);
-      } else {
-        throw err;
-      }
-    } finally {
-      await tab.close();
-    }
-
-    return screenshot;
+    return withRetries(options.chromeRetries, CAPTURING_SCREENSHOT_RETRY_BACKOFF)(async () => {
+      const tab = await launchNewTab(tabOptions);
+      let screenshot;
+      try {
+        await withTimeout(options.chromeLoadTimeout)(tab.loadUrl(url, selector));
+        screenshot = await tab.captureScreenshot(selector);
+      } catch (err) {
+        if (err instanceof TimeoutError) {
+          debug(`Timed out waiting for "${url}" to load`);
+        }
+
+        throw err;
+      } finally {
+        await tab.close();
+      }
+
+      return screenshot;
+    })();
   }
 
   return {
```

**Comment by Urugash** [comment]
Is this fix going to be included in a new version of Loki ? My team still can't use Loki in their CI pipeline for the moment

**Comment by acapro** [comment]
Just wanted to post my fix as well for anyone else facing this issue.  Thanks @kirilldronkin for the research and explanation! I tried the patch as posted, but for me it didn't work. I solved this a bit different, by just making sure that undefined would not get returned. Here is what I have:

```patch
diff --git a/node_modules/@loki/target-chrome-core/src/create-chrome-target.js b/node_modules/@loki/target-chrome-core/src/create-chrome-target.js
index 69878ef..f72ca1e 100644
--- a/node_modules/@loki/target-chrome-core/src/create-chrome-target.js
+++ b/node_modules/@loki/target-chrome-core/src/create-chrome-target.js
@@ -410,6 +410,7 @@ function createChromeTarget(
     } catch (err) {
       if (err instanceof TimeoutError) {
         debug(`Timed out waiting for "${url}" to load`);
+        throw err; // This line is added to rethrow the error instead of just logging it
       } else {
         throw err;
       }
@@ -417,6 +418,10 @@ function createChromeTarget(
       await tab.close();
     }
 
+    if (!screenshot) {
+      throw new Error('Screenshot is undefined'); // Ensure that screenshot is not undefined before returning it
+    }
+
     return screenshot;
   }
 

```

**Comment by Ajdija** [comment]
This was a showstopper for us for a long time. Some of the systems work with above patches and some don't

**Comment by gblessy** [comment]
I also have this issue after the update to loki 0.34.0.  Is this issue going to be fixed in the next version of loki?

**Comment by freshollie** [comment]
Still experiencing this

**Comment by Tarkan2467** [comment]
Seeing this as well on Node 22 and React 18. A couple versions behind on Storybook at `6.5.16` — unsure if that's related.

Loki version `0.31.2` is the last working version in my case — all versions `0.32.0` and newer are showing this error. Would love to have a fix for this.

**Comment by levymetal** [comment]
@Tarkan2467 The main difference between `0.31.2` and `0.32.0` is that the static files are now served from an http server. The patches in this thread didn't resolve `ERR_INVALID_ARG_TYPE` for me, however I found that swapping out the node http server for express solved this and other issues with fetch failures, and now I'm able to run Storybook `8` & loki `0.35.1` without error.

Using [patch-package](https://www.npmjs.com/package/patch-package), the custom http server in `create-static-server.js` can be replaced with a simple express app (just ensure `express` is added to your `package.json`):

```js
const express = require('express');

const createStaticServer = (dir) => {
  const setHeaders = (res) => {
    res.setHeader('Cache-Control', 'no-store, must-revalidate');
  };
  const app = express();
  app.use(express.static(dir, { setHeaders }));
  return app;
};

module.exports = { createStaticServer };
```

Then `create-chrome-app-target.js` & `create-chrome-docker-target.js` need a small tweak to assign `staticServer` to the result of `listen()`:

```ls
staticServer = createStaticServer(staticServerPath).listen(staticServerPort);
```

This may also resolve other issues such as https://github.com/oblador/loki/issues/512, https://github.com/oblador/loki/issues/523, and https://github.com/oblador/loki/issues/535. I don't really understand what's wrong with the custom server, and I personally prefer the simplicity of Express, but I'm not sure if the maintainers would prefer to address the issues with the custom server instead of adding a dependency on `express`. 

NB: Chrome should probably wait for the server to start to avoid issues like https://github.com/oblador/loki/issues/528, but that requires a bit more massaging since `listen` is not async, and I'm not sure whether it's really necessary or not - I haven't had any issues with the above patch that doesn't wait.

**Comment by Tarkan2467** [comment]
Had to revisit this last week as Loki `0.31.2` (the version I was stuck on) stopped working locally for me as of Docker Desktop `4.51.0`. I can confirm that manual patching to apply @levymetal's solution from https://github.com/oblador/loki/issues/401#issuecomment-2735003836 solved my issues.

Patches I applied:

- `@loki+core+0.35.0.patch` (updates to `create-static-server.js`)
- `@loki+target-chrome-app+0.35.0.patch` (updates to `create-chrome-app-target.js`)
- `@loki+target-chrome-docker+0.35.0.patch` (updates to `create-chrome-docker-target.js`)

Thank you very much for the help! Hopefully the package will receive an official update at some point.
