### ISSUE TITLE
loki always get test succeed in a project working with RxJS and  recompose 

### ISSUE THREAD

**Issue by erochOnGit** [oblador/loki#5]
everything is in the title ... i made a project to let you test it : 
https://github.com/erochOnGit/reactstorybookdockerRxJS

![capture du 2017-09-11 16-47-19](https://user-images.githubusercontent.com/24712827/30315532-94d9ff4e-97a4-11e7-9ad1-ca1d6e0af4ab.png)

Tell me if you have some issue with the setup
i'm using node 8.* and loki 0.6.0

**Comment by erochOnGit** [comment]
to be precise the line that make all the project run out of the road is : 
`import { Observable } from "rxjs";`

**Comment by oblador** [comment]
Hey, with 0.6.0 the way filenames are generated changed slightly for non ascii characters, so I'd guess loki can't find the reference files and just accepts the story. Try passing `--requireReference` to fail in those cases (that's what I do in CI).

**Comment by erochOnGit** [comment]
the yarn loki update --requireReference does not work more than without --requireReference

and in the v 0.6.1
i get an error message after the test pass : 
 Error: Uncaught [TypeError: source.close is not a function]
    at reportException (/home/emile/projet/reactLOKIALLPROJECT/reactLokiProject/reactstorybookdocker/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:63:24)
    at Timeout.callback (/home/emile/projet/reactLOKIALLPROJECT/reactLokiProject/reactstorybookdocker/node_modules/jsdom/lib/jsdom/browser/Window.js:547:7)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5) TypeError: source.close is not a function
    at handleDisconnect (evalmachine.<anonymous>:56366:12)
    at Window.<anonymous> (evalmachine.<anonymous>:56341:7)
    at Timeout.callback (/home/emile/projet/reactLOKIALLPROJECT/reactLokiProject/reactstorybookdocker/node_modules/jsdom/lib/jsdom/browser/Window.js:545:19)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
Done in 23.37s.
is that normal ?

**Comment by oblador** [comment]
I believe this should be fixed as of [0.10.0](https://github.com/oblador/loki/releases/tag/v0.10.0). Please reopen if the problem persists.
