### ISSUE TITLE
Unable to run loki in react storybook

### ISSUE THREAD

**Issue by ktj** [oblador/loki#50]
Hi,

I'm unable to run loki in my web storybook. I'm able to run it react-native storybook though.

I can run the react example fine. I tried downgrading to storybook 3.1.6 - 3.1.7, but that didn't help either.
```
loki update v0.8.0
 ❯ Chrome (docker)
   ✔ Start
   ✖ Fetch list of stories
     → Cannot read property 'prototype' of undefined
     Test chrome.laptop
     Test chrome.iphone7
     Stop
Cannot read property 'prototype' of undefined
Error: Cannot read property 'prototype' of undefined
    at createError (/Users/julius/workspace/shared-components/storybooks/web/node_modules/loki/src/targets/chrome/fetch-storybook.js:10:14)
    at Worker.worker.on.message (/Users/julius/workspace/shared-components/storybooks/web/node_modules/loki/src/targets/chrome/fetch-storybook.js:33:16)
    at Worker.emit (events.js:164:20)
    at ChildProcess.Worker.process.on (internal/cluster/worker.js:28:12)
    at ChildProcess.emit (events.js:159:13)
    at emit (internal/child_process.js:790:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
error Command failed with exit code 1.

```

I tried with and without docker, but I always get the same error.
Any idea what I should try?

Is there some known addon that might cause problems with loki?

**Comment by ktj** [comment]
Do I need some polyfills for loki?
