### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'ReactCurrentOwner')

### ISSUE THREAD

**Issue by EvgeniyWis** [oblador/loki#531]
When running loki I get this error:
```
D:\FrontEnd\Projects\SuncovRussian\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53        
throw ex;
        ^

TypeError: Cannot read properties of undefined (reading 'ReactCurrentOwner')
    at Object.$$$reconciler [as default] (D:\FrontEnd\Projects\SuncovRussian\node_modules\ink\node_modules\react-reconciler\cjs\react-reconciler.development.js:344:46)
    at Object.<anonymous> (D:\FrontEnd\Projects\SuncovRussian\node_modules\ink\build\reconciler.js:21:45) 
    at Module._compile (node:internal/modules/cjs/loader:1740:14)
    at Object..js (node:internal/modules/cjs/loader:1905:10)
    at Module.load (node:internal/modules/cjs/loader:1474:32)
    at Function._load (node:internal/modules/cjs/loader:1286:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:234:24)
    at Module.require (node:internal/modules/cjs/loader:1496:12)
    at require (node:internal/modules/helpers:135:16)

Node.js v23.5.0
```

I looked at the react-reconciler.development.js file and concluded that the issue is that the react-reconciler library that loki uses uses React.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED, which is highly discouraged. Does anyone have any idea how this can be affected?

**Comment by VytautasEilika** [comment]
Same problem

```
/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

TypeError: Cannot read properties of undefined (reading 'ReactCurrentOwner')
    at Object.$$$reconciler [as default] (/home/v/e/node_modules/react-reconciler/cjs/react-reconciler.development.js:344:46)
    at Object.<anonymous> (/home/v/e/node_modules/ink/build/reconciler.js:21:45)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/v/e/node_modules/ink/build/ink.js:31:38)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)

Node.js v21.7.3
```

**Comment by KrisWis** [comment]
Given this [response](https://github.com/vadimdemedes/ink/issues/688), it seems as if we have no influence on this

**Comment by EvgeniyWis** [comment]
> Same problem
> 
> ```
> /node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
>         throw ex;
>         ^
> 
> TypeError: Cannot read properties of undefined (reading 'ReactCurrentOwner')
>     at Object.$$$reconciler [as default] (/home/v/e/node_modules/react-reconciler/cjs/react-reconciler.development.js:344:46)
>     at Object.<anonymous> (/home/v/e/node_modules/ink/build/reconciler.js:21:45)
>     at Module._compile (node:internal/modules/cjs/loader:1368:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
>     at Module.load (node:internal/modules/cjs/loader:1205:32)
>     at Module._load (node:internal/modules/cjs/loader:1021:12)
>     at Module.require (node:internal/modules/cjs/loader:1230:19)
>     at require (node:internal/modules/helpers:179:18)
>     at Object.<anonymous> (/home/v/e/node_modules/ink/build/ink.js:31:38)
>     at Module._compile (node:internal/modules/cjs/loader:1368:14)
> 
> Node.js v21.7.3
> ```

Given this [response](https://github.com/vadimdemedes/ink/issues/688), it seems as if we have no influence on this

**Comment by jiroler** [comment]
I've got the same error after updating react to 19. This fix in `package.json` works for me:
```json
    "overrides": {
        "ink": {
            "react": "^17.0.2"
        }
    },
```

The version `"^17.0.2"` is from `@loki/runner` package

**Comment by EvgeniyWis** [comment]
> I've got the same error after updating react to 19. This fix in `package.json` works for me:
> 
>     "overrides": {
>         "ink": {
>             "react": "^17.0.2"
>         }
>     },
> The version `"^17.0.2"` is from `@loki/runner` package

It doesn`t work for me :(

**Comment by jiroler** [comment]
@EvgeniyWis Do you have the same error?

**Comment by EvgeniyWis** [comment]
> @EvgeniyWis Do you have the same error?

Yes

**Comment by jiroler** [comment]
@EvgeniyWis You should remove `package-lock.json` file, `node_modules` folder, then apply changes and run `npm i`.
I would take a look at your repo if it is public

**Comment by EvgeniyWis** [comment]
> @EvgeniyWis You should remove `package-lock.json` file, `node_modules` folder, then apply changes and run `npm i`.
> I would take a look at your repo if it is public

https://github.com/EvgeniyWis/SuncovRussian - there is my repo

**Comment by jiroler** [comment]
@EvgeniyWis  I've made the changes and `loki` works. There is no `ReactCurrentOwner` error, but another errors appear.
I think the main goal is achieved - `loki` fetches stories. The rest is on your end :)
![,Image](https://github.com/user-attachments/assets/6bbb61e8-ee55-46a4-833b-0b33faa91c3f)
```
  "overrides": {
    "ink": {
      "react": "^17.0.2"
    }
  },
  "loki": {
    "configurations": {
      "chrome": {
        "target": "chrome.app",
        "width": 1440,
        "height": 900,
        "deviceScaleFactor": 1,
        "mobile": false
      }
    }
```

```
% npx loki test --port 6006 
loki test v0.35.0
(node:41401) NOTE: The AWS SDK for JavaScript (v2) is in maintenance mode.
 SDK releases are limited to address critical bug fixes and security issues only.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the blog post at https://a.co/cUPnyil
(Use `node --trace-warnings ...` to show where the warning was created)
 FAIL  chrome.app/chrome/Features/Test
       With One Correct Answer
       2 requests failed to load; , 
 FAIL  chrome.app/chrome/Features/PartsOfSpeachItem
       Primary
       2 requests failed to load; , 
 FAIL  chrome.app/chrome/Features/Test
       With One Correct Answer
       2 requests failed to load; , 
       With Some Correct Answers
       2 requests failed to load; , 
 FAIL  chrome.app/chrome/Pages/Dictants
       Primary
       3 requests failed to load; , , https://xn----8sbezalrcg2atd4b.xn--p1ai/api/v1/tests
 FAIL  chrome.app/chrome/Pages/Main
       Primary
       3 requests failed to load; , , https://xn----8sbezalrcg2atd4b.xn--p1ai/api/v1/tests
 FAIL  chrome.app/chrome/Entities/TheoryItem
       Primary
       2 requests failed to load; , 
 FAIL  chrome.app/chrome/Pages/NotFound
       Primary
       3 requests failed to load; , , https://xn----8sbezalrcg2atd4b.xn--p1ai/api/v1/tests
 FAIL  chrome.app/chrome/Pages/PartsOfSpeachPage
...
```

**Comment by EvgeniyWis** [comment]
> "overrides": {
>     "ink": {
>       "react": "^17.0.2"
>     }
>   },
>   "loki": {
>     "configurations": {
>       "chrome": {
>         "target": "chrome.app",
>         "width": 1440,
>         "height": 900,
>         "deviceScaleFactor": 1,
>         "mobile": false
>       }
>     }

Thank you so much! I had to do a lot of manipulations, but your help made an important first step in solving this problem)

**Comment by Zaynalobiddin** [comment]
This solution worked for me as well. Thank you @jiroler for the solution, and thank you @EvgeniyWis for quite good describing the issue

**Comment by Anxhul10** [comment]
``` 2 requests failed to load ```  I am facing this kind of error if you all managed to fix this can you please share the solution I tried delay hook on that particular story but i am testing in multiple viewport so delay hook is used in only one viewpoer  can you please have a look  https://github.com/oblador/loki/issues/543 . 
Any help is appreciated !!

**Comment by jiroler** [comment]
@Anxhul10 I think you should test async examples locally (`examples/react/src/async`) and try to integrate this into your project

**Comment by Anxhul10** [comment]
> [@Anxhul10](https://github.com/Anxhul10) I think you should test async examples locally (`examples/react/src/async`) and try to integrate this into your project

``` 
➜  react git:(master) ✗ yarn loki test
yarn run v1.22.22
$ /home/anxhul/CodeVault/g-project/loki/node_modules/.bin/loki test
loki test v0.35.0

Connected!
 PASS  chrome.docker/chrome.laptop/isLokiRunning()
 PASS  chrome.docker/chrome.laptop/Fetch Components
 PASS  chrome.docker/chrome.laptop/Decorators
 PASS  chrome.docker/chrome.laptop/Media
 PASS  chrome.docker/chrome.laptop/CSF
 FAIL  chrome.docker/chrome.laptop/Animation
       with react-motion
       1 request failed to load; http://192.168.29.108:6006/runtime-error
 PASS  chrome.docker/chrome.laptop/Text
 PASS  chrome.docker/chrome.laptop/FocusedInput
 PASS  chrome.docker/chrome.laptop/Asynchronous render
 PASS  chrome.docker/chrome.laptop/Hover
 PASS  chrome.docker/chrome.laptop/Long Element
 PASS  chrome.docker/chrome.laptop/Positions
 PASS  chrome.docker/chrome.laptop/Multiple elements
 PASS  chrome.docker/chrome.laptop/Zero height
 PASS  chrome.docker/chrome.iphone7/isLokiRunning()
 PASS  chrome.docker/chrome.iphone7/Fetch Components
 PASS  chrome.docker/chrome.iphone7/Decorators
 PASS  chrome.docker/chrome.iphone7/Media
 PASS  chrome.docker/chrome.iphone7/CSF
 FAIL  chrome.docker/chrome.iphone7/Animation
       with react-motion
       1 request failed to load; http://192.168.29.108:6006/runtime-error
 PASS  chrome.docker/chrome.iphone7/Text
 PASS  chrome.docker/chrome.iphone7/FocusedInput
 PASS  chrome.docker/chrome.iphone7/Hover
 PASS  chrome.docker/chrome.iphone7/Asynchronous render
 PASS  chrome.docker/chrome.iphone7/Long Element
 PASS  chrome.docker/chrome.iphone7/Positions
 PASS  chrome.docker/chrome.iphone7/Multiple elements
 PASS  chrome.docker/chrome.iphone7/Zero height
 PASS  chrome.docker/chrome.a4/isLokiRunning()
 PASS  chrome.docker/chrome.a4/Fetch Components
 PASS  chrome.docker/chrome.a4/Decorators
 PASS  chrome.docker/chrome.a4/Media
 PASS  chrome.docker/chrome.a4/CSF
 FAIL  chrome.docker/chrome.a4/Animation
       with react-motion
       1 request failed to load; http://192.168.29.108:6006/runtime-error
 PASS  chrome.docker/chrome.a4/Text
 PASS  chrome.docker/chrome.a4/FocusedInput
 PASS  chrome.docker/chrome.a4/Hover
 PASS  chrome.docker/chrome.a4/Asynchronous render
 PASS  chrome.docker/chrome.a4/Long Element
 PASS  chrome.docker/chrome.a4/Positions
 PASS  chrome.docker/chrome.a4/Multiple elements
 PASS  chrome.docker/chrome.a4/Zero height
 FAIL  chrome.docker
Some visual tests failed to run
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
➜  react git:(master) ✗ 
```

i tried but oblador/loki react example also give similar errors

**Comment by Anxhul10** [comment]
this is solved add this in loki.config.js ```  fetchFailIgnore: 'localhost:1234/get|192\\.168\\.29\\.108:6006/runtime-error',```
Thanks for the help !! really appreciated
